apiVersion: apps/v1
kind: Deployment
metadata:
  name: crypto-test
spec:
  replicas: 1
  selector:
    matchLabels:
      app: crypto-test
  template:
    metadata:
      labels:
        app: crypto-test
    spec:
      containers:
      - name: crypto-test
        image: ghcr.io/ryan44c8/crypto-test:c1caa0858ff67d09ab71ccb94bed486968e87921
        ports:
        - containerPort: 3000
